version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "CropCoder"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
